// <auto-generated />
using System;
using LemadDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LemadDb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221102181211_test10")]
    partial class test10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LemadDb.Domain.Entities.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWithDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWithTaxes")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Command");
                });

            modelBuilder.Entity("LemadDb.Domain.Entities.CommandProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.ToTable("CommandProduct");
                });

            modelBuilder.Entity("LemadDb.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("CommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("MaxContractTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<string>("Quote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateNaissance = new DateTime(1981, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teflonso, the spanish GOAT",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Fernando Alonso",
                            Path = "wwwroot/img/products/drivers/FernandoAlonso.png",
                            Price = 20000000m,
                            ProductCategory = 0,
                            Quote = "I am one of the best to have raced in F1. I am probably not fastest in qualifying, or the wet, but I am 9.5 in all areas. I try to benefit from that.",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DateNaissance = new DateTime(1996, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Esteban Ocon",
                            Path = "wwwroot/img/products/drivers/EstebanOcon.png",
                            Price = 5000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DateNaissance = new DateTime(1997, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mad Max",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Max Verstappen",
                            Path = "wwwroot/img/products/drivers/MaxVerstappen.png",
                            Price = 25000000m,
                            ProductCategory = 0,
                            Quote = "Mistakes happen, and they happen to the best of us.",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            DateNaissance = new DateTime(1990, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Checo",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Sergio Perez",
                            Path = "wwwroot/img/products/drivers/SergioPerez.png",
                            Price = 8000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            DateNaissance = new DateTime(1997, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Charles Leclerc",
                            Path = "wwwroot/img/products/drivers/CharlesLeclerc.png",
                            Price = 12000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DateNaissance = new DateTime(1994, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Carlos Sainz",
                            Path = "wwwroot/img/products/drivers/CarlosSainz.png",
                            Price = 10000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            DateNaissance = new DateTime(1985, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Lewis Hamilton",
                            Path = "wwwroot/img/products/drivers/LewisHamilton.png",
                            Price = 40000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            DateNaissance = new DateTime(1998, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 2,
                            MaxContractTime = 5,
                            Name = "George Russell",
                            Path = "wwwroot/img/products/drivers/GeorgeRussell.png",
                            Price = 5000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 9,
                            DateNaissance = new DateTime(1999, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Lando Norris",
                            Path = "wwwroot/img/products/drivers/LandoNorris.png",
                            Price = 20000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            DateNaissance = new DateTime(1989, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Daniel Ricciardo",
                            Path = "wwwroot/img/products/drivers/DanielRicciardo.png",
                            Price = 15000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            DateNaissance = new DateTime(1989, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Valtteri Bottas",
                            Path = "wwwroot/img/products/drivers/ValtteriBottas.png",
                            Price = 10000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            DateNaissance = new DateTime(1999, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Zhou Guanyu",
                            Path = "wwwroot/img/products/drivers/ZhouGuanyu.png",
                            Price = 1000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            DateNaissance = new DateTime(1996, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 80,
                            MaxContractTime = 5,
                            Name = "Pierre Gasly",
                            Path = "wwwroot/img/products/drivers/PierreGasly.png",
                            Price = 5000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 14,
                            DateNaissance = new DateTime(2000, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Yuki Tsunoda",
                            Path = "wwwroot/img/products/drivers/YukiTsunoda.png",
                            Price = 750000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            DateNaissance = new DateTime(1995, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 60,
                            MaxContractTime = 5,
                            Name = "Nicholas Latifi",
                            Path = "wwwroot/img/products/drivers/NicholasLatifi.png",
                            Price = 1000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 16,
                            DateNaissance = new DateTime(1996, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Alexander Albon",
                            Path = "wwwroot/img/products/drivers/AlexanderAlbon.png",
                            Price = 2000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            DateNaissance = new DateTime(1987, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Sebastian Vettel",
                            Path = "wwwroot/img/products/drivers/SebastianVettel.png",
                            Price = 15000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            DateNaissance = new DateTime(1998, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 49,
                            MaxContractTime = 5,
                            Name = "Lance Stroll",
                            Path = "wwwroot/img/products/drivers/LanceStroll.png",
                            Price = 10000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 19,
                            DateNaissance = new DateTime(1992, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 22,
                            MaxContractTime = 5,
                            Name = "Kevin Magnussen",
                            Path = "wwwroot/img/products/drivers/KevinMagnussen.png",
                            Price = 6000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 2
                        },
                        new
                        {
                            Id = 20,
                            DateNaissance = new DateTime(1999, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mick Schumacher",
                            Path = "wwwroot/img/products/drivers/MickSchumacher.png",
                            Price = 1000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mattia Binotto",
                            Path = "wwwroot/img/products/principals/MattiaBinotto.png",
                            Price = 3000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Frédéric Vasseur",
                            Path = "wwwroot/img/products/principals/FredericVasseur.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 2
                        },
                        new
                        {
                            Id = 23,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 25,
                            MaxContractTime = 5,
                            Name = "Franz Tost",
                            Path = "wwwroot/img/products/principals/FranzTost.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Otmar Szafnauer",
                            Path = "wwwroot/img/products/principals/OtmarSzafnauer.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 34,
                            MaxContractTime = 5,
                            Name = "Guenther Steiner",
                            Path = "wwwroot/img/products/principals/GuentherSteiner.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 26,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Andreas Seidl",
                            Path = "wwwroot/img/products/principals/AndreasSeidl.png",
                            Price = 2000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 27,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Toto Wolff",
                            Path = "wwwroot/img/products/principals/TotoWolff.png",
                            Price = 9100000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 13,
                            MaxContractTime = 5,
                            Name = "Christian Horner",
                            Path = "wwwroot/img/products/principals/ChristianHorner.png",
                            Price = 10000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 29,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jost Capito",
                            Path = "wwwroot/img/products/principals/JostCapito.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 1
                        },
                        new
                        {
                            Id = 30,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mike Krack",
                            Path = "wwwroot/img/products/principals/MikeKrack.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 31,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Red Bull Powertrains",
                            Path = "wwwroot/img/products/powerunits/RedBullPowertrains.png",
                            Price = 50000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Ferrari engines",
                            Path = "wwwroot/img/products/powerunits/FerrariEngines.png",
                            Price = 40000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 15,
                            MaxContractTime = 5,
                            Name = "Mercedes engines",
                            Path = "wwwroot/img/products/powerunits/MercedesEngines.png",
                            Price = 35000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 2
                        },
                        new
                        {
                            Id = 34,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Renault engines",
                            Path = "wwwroot/img/products/powerunits/RenaultEngines.png",
                            Price = 30000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 35,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jody Egginton",
                            Path = "wwwroot/img/products/technicalchiefs/JodyEgginton.png",
                            Price = 600000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 36,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Pierre Washe",
                            Path = "wwwroot/img/products/technicalchiefs/PierreWashe.png",
                            Price = 2000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 37,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 10,
                            MaxContractTime = 5,
                            Name = "Enrico Cardile",
                            Path = "wwwroot/img/products/technicalchiefs/EnricoCardile.png",
                            Price = 1500000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 38,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Simone Resta",
                            Path = "wwwroot/img/products/technicalchiefs/SimoneResta.png",
                            Price = 1000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Matt Harman",
                            Path = "wwwroot/img/products/technicalchiefs/MattHarman.png",
                            Price = 1000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mike Elliott",
                            Path = "wwwroot/img/products/technicalchiefs/MikeElliott.png",
                            Price = 1000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 41,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 10,
                            MaxContractTime = 5,
                            Name = "Ben Watkins",
                            Path = "wwwroot/img/products/technicalchiefs/BenWatkins.png",
                            Price = 800000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 42,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Francois-Xavier Demaison",
                            Path = "wwwroot/img/products/technicalchiefs/FrancoisXavierDemaison.png",
                            Price = 750000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 43,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jan Monchaux",
                            Path = "wwwroot/img/products/technicalchiefs/JanMonchaux.png",
                            Price = 500000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 44,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Andrew Green",
                            Path = "wwwroot/img/products/technicalchiefs/AndrewGreen.png",
                            Price = 400000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 45,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Ben Michell",
                            Path = "wwwroot/img/products/raceengineers/BenMichell.png",
                            Price = 2000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 46,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Chris Cronin",
                            Path = "wwwroot/img/products/raceengineers/ChrisCronin.png",
                            Price = 1500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 47,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jorn Becker",
                            Path = "wwwroot/img/products/raceengineers/JornBecker.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 48,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 10,
                            MaxContractTime = 5,
                            Name = "Alex Chan",
                            Path = "wwwroot/img/products/raceengineers/AlexChan.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 49,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mattia Spini",
                            Path = "wwwroot/img/products/raceengineers/MattiaSpini.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 50,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 5,
                            MaxContractTime = 5,
                            Name = "Pierre Hamelin",
                            Path = "wwwroot/img/products/raceengineers/PierreHamelin.png",
                            Price = 800000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 51,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Gary Gannon",
                            Path = "wwwroot/img/products/raceengineers/GaryGannon.png",
                            Price = 750000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 52,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Ed Regan",
                            Path = "wwwroot/img/products/raceengineers/EdRegan.png",
                            Price = 600000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 53,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Gaetan Jego",
                            Path = "wwwroot/img/products/raceengineers/GaetanJego.png",
                            Price = 500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 54,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "James Urwin",
                            Path = "wwwroot/img/products/raceengineers/JamesUrwin.png",
                            Price = 400000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 55,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 5,
                            MaxContractTime = 5,
                            Name = "Josh Pecket",
                            Path = "wwwroot/img/products/raceengineers/JoshPecket.png",
                            Price = 2000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 56,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Karel Loos",
                            Path = "wwwroot/img/products/raceengineers/KarelLoos.png",
                            Price = 1500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 57,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Riccardo Musconi",
                            Path = "wwwroot/img/products/raceengineers/RiccardoMusconi.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 58,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Peter Bonnington",
                            Path = "wwwroot/img/products/raceengineers/PeterBonnington.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 59,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Gianpiero Lambiase",
                            Path = "wwwroot/img/products/raceengineers/GianpieroLambiase.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 60,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Hugh Bird",
                            Path = "wwwroot/img/products/raceengineers/HughBird.png",
                            Price = 800000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 61,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jason Prior",
                            Path = "wwwroot/img/products/raceengineers/JasonPrior.png",
                            Price = 750000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 62,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Christopher Hayes",
                            Path = "wwwroot/img/products/raceengineers/CristopherHayes.png",
                            Price = 600000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 63,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Riccardo Adami",
                            Path = "wwwroot/img/products/raceengineers/RiccardoAdami.png",
                            Price = 500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 64,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Xavier Marcos Pardos",
                            Path = "wwwroot/img/products/raceengineers/XavierMarcosPardos.png",
                            Price = 400000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        });
                });

            modelBuilder.Entity("LemadDb.Domain.User.AddressUser", b =>
                {
                    b.Property<Guid>("AdresseCiviqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AdresseCiviqueId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("AddressUser");

                    b.HasData(
                        new
                        {
                            AdresseCiviqueId = new Guid("2f8b635c-6d91-4c37-8cc7-e1dfaa68d3e1"),
                            ApplicationUserId = "509b57a1-3237-43df-9991-d249f5bc55ab"
                        },
                        new
                        {
                            AdresseCiviqueId = new Guid("2f8b635c-6d91-4c37-8cc7-e1dfaa68d3e1"),
                            ApplicationUserId = "5251a5c4-a28a-4cfd-90ec-c7a9e8180e84"
                        },
                        new
                        {
                            AdresseCiviqueId = new Guid("2f8b635c-6d91-4c37-8cc7-e1dfaa68d3e1"),
                            ApplicationUserId = "bde03042-809f-4d36-92df-3e1326b1efc9"
                        },
                        new
                        {
                            AdresseCiviqueId = new Guid("2f8b635c-6d91-4c37-8cc7-e1dfaa68d3e1"),
                            ApplicationUserId = "67aa9680-d861-4bd3-bf7c-307ed12d6cf3"
                        },
                        new
                        {
                            AdresseCiviqueId = new Guid("570781fd-6375-4a2f-bda1-afd52bd3eea7"),
                            ApplicationUserId = "919f85fd-1570-4094-97a9-c46b26a8936d"
                        });
                });

            modelBuilder.Entity("LemadDb.Domain.User.AdresseCivique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CivicAddresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f8b635c-6d91-4c37-8cc7-e1dfaa68d3e1"),
                            Address = "3000 Av. Boullé",
                            City = "Saint-Hyacinthe",
                            Country = "Canada",
                            PostalCode = "J2S 1H9",
                            Province = "Québec"
                        },
                        new
                        {
                            Id = new Guid("570781fd-6375-4a2f-bda1-afd52bd3eea7"),
                            Address = "1899 Henri-Becquerel",
                            City = "Sainte-Julie",
                            Country = "Canada",
                            PostalCode = "J3E 1V6",
                            Province = "Québec"
                        });
                });

            modelBuilder.Entity("LemadDb.Domain.User.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Cellphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "8b352816-b6b3-4ca9-b776-c340f26f2822",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "622bfe96-b311-4bf8-8c78-4dd1dc91cc90",
                            Email = "admin@lemadrid.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LEMADRID.COM",
                            NormalizedUserName = "ADMIN@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOV/v4+i8WiD8r7zjy8FZM/BctrZwq2GQWp0HiMVD9Ul3TNIYQhxlutnd2zbuBXIXA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ab39aab7-3a0e-4b93-8487-bebf53dba680",
                            TwoFactorEnabled = false,
                            UserName = "admin@lemadrid.com"
                        },
                        new
                        {
                            Id = "509b57a1-3237-43df-9991-d249f5bc55ab",
                            AccessFailedCount = 0,
                            Cellphone = "(450)-773-6800",
                            ConcurrencyStamp = "91655652-6610-40e4-8e5d-ded0ea1af120",
                            Email = "hugo@lemadrid.com",
                            EmailConfirmed = false,
                            FirstName = "Hugo",
                            LastName = "Lapointe",
                            LockoutEnabled = false,
                            NormalizedEmail = "HUGO@LEMADRID.COM",
                            NormalizedUserName = "HUGO@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEM2XM43xb5waieiKEBVdb/KHyAr18rrL1nxVxVKsR5qiL9rbHVXzBANL/rD4T42kdw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57fa00e9-143e-48ca-a6c7-db681c8723ed",
                            TwoFactorEnabled = false,
                            UserName = "hugo@lemadrid.com"
                        },
                        new
                        {
                            Id = "919f85fd-1570-4094-97a9-c46b26a8936d",
                            AccessFailedCount = 0,
                            Cellphone = "(450)-649-8594",
                            ConcurrencyStamp = "76965fce-62bf-4714-add4-d53ddb69f553",
                            Email = "karl.mainville@lemadrid.com",
                            EmailConfirmed = false,
                            FirstName = "Karl",
                            LastName = "Mainville",
                            LockoutEnabled = false,
                            NormalizedEmail = "KARL.MAINVILLE@LEMADRID.COM",
                            NormalizedUserName = "KARL.MAINVILLE@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJCxrXKLxWgr0i5Z2i7uKYl8W7w9goO0EaL1UT0ZJCZXaW83TWGYScpST102iyZpSw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49ffba74-b56d-4555-ad15-09c69cb141b2",
                            TwoFactorEnabled = false,
                            UserName = "karl.mainville@lemadrid.com"
                        },
                        new
                        {
                            Id = "5251a5c4-a28a-4cfd-90ec-c7a9e8180e84",
                            AccessFailedCount = 0,
                            Cellphone = "(450)-538-3982",
                            ConcurrencyStamp = "7cfc741d-746c-4a44-b04f-759bc967552d",
                            Email = "maxime.lefebvre@lemadrid.com",
                            EmailConfirmed = false,
                            FirstName = "Maxime",
                            LastName = "Lefebvre",
                            LockoutEnabled = false,
                            NormalizedEmail = "MAXIME.LEFEBVRE@LEMADRID.COM",
                            NormalizedUserName = "MAXIME.LEFEBVRE@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAED8AxBmy4g8o4KpCXMx3Unr8sWfTkDt+i1FwJtnXJdDTQCPzzEMUOla6++nVwX12JQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "80a97b0c-6dc1-4ab2-9ccc-2ead41bd4cf7",
                            TwoFactorEnabled = false,
                            UserName = "maxime.lefebvre@lemadrid.com"
                        },
                        new
                        {
                            Id = "bde03042-809f-4d36-92df-3e1326b1efc9",
                            AccessFailedCount = 0,
                            Cellphone = "(450)-213-5697",
                            ConcurrencyStamp = "8c351df9-dd69-4c1c-bf37-a15b4780467c",
                            Email = "louis.garceau@lemadrid.com",
                            EmailConfirmed = false,
                            FirstName = "Louis",
                            LastName = "Garceau",
                            LockoutEnabled = false,
                            NormalizedEmail = "LOUIS.GARCEAU@LEMADRID.COM",
                            NormalizedUserName = "LOUIS.GARCEAU@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENJluxqgXO8bPqLBf3bAvvx1YA46EWIF+K7sxvnAnX9AnjLepEnSZnQ6t/ipwM5gXQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e78ed78-92ca-4d73-8604-13c0f4044927",
                            TwoFactorEnabled = false,
                            UserName = "louis.garceau@lemadrid.com"
                        },
                        new
                        {
                            Id = "67aa9680-d861-4bd3-bf7c-307ed12d6cf3",
                            AccessFailedCount = 0,
                            Cellphone = "(450)-789-4673",
                            ConcurrencyStamp = "21276e26-1c93-4b1b-b86e-00ecc815b770",
                            Email = "laurent.brochu@lemadrid.com",
                            EmailConfirmed = false,
                            FirstName = "Laurent",
                            LastName = "Brochu",
                            LockoutEnabled = false,
                            NormalizedEmail = "LAURENT.BROCHU@LEMADRID.COM",
                            NormalizedUserName = "LAURENT.BROCHU@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEB7LOaNL4f7iU0qCyo7rP5modiWzaNi0PW5RalUNoRMGdtVmsZF5qdCfxE4qtfwKLg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4c5a7a07-676c-435a-ba08-67a79c848a2b",
                            TwoFactorEnabled = false,
                            UserName = "laurent.brochu@lemadrid.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "2c268261-3e08-45bb-8837-febaa8e8588b",
                            ConcurrencyStamp = "fd813c03-4b5c-4e19-a10f-a61db8b7e5de",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "88fd8308-6f3a-4d7d-a5fc-b3aad5c0b318",
                            ConcurrencyStamp = "e3f9fa8f-fce8-4d81-ac81-bcdd014a984b",
                            Name = "buyer",
                            NormalizedName = "BUYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "8b352816-b6b3-4ca9-b776-c340f26f2822",
                            RoleId = "2c268261-3e08-45bb-8837-febaa8e8588b"
                        },
                        new
                        {
                            UserId = "509b57a1-3237-43df-9991-d249f5bc55ab",
                            RoleId = "88fd8308-6f3a-4d7d-a5fc-b3aad5c0b318"
                        },
                        new
                        {
                            UserId = "919f85fd-1570-4094-97a9-c46b26a8936d",
                            RoleId = "88fd8308-6f3a-4d7d-a5fc-b3aad5c0b318"
                        },
                        new
                        {
                            UserId = "5251a5c4-a28a-4cfd-90ec-c7a9e8180e84",
                            RoleId = "88fd8308-6f3a-4d7d-a5fc-b3aad5c0b318"
                        },
                        new
                        {
                            UserId = "bde03042-809f-4d36-92df-3e1326b1efc9",
                            RoleId = "88fd8308-6f3a-4d7d-a5fc-b3aad5c0b318"
                        },
                        new
                        {
                            UserId = "67aa9680-d861-4bd3-bf7c-307ed12d6cf3",
                            RoleId = "88fd8308-6f3a-4d7d-a5fc-b3aad5c0b318"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("LemadDb.Domain.Entities.Command", b =>
                {
                    b.HasOne("LemadDb.Domain.User.ApplicationUser", "ApplicationUser")
                        .WithMany("Commands")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("LemadDb.Domain.Entities.CommandProduct", b =>
                {
                    b.HasOne("LemadDb.Domain.Entities.Command", null)
                        .WithMany("ProductIDs")
                        .HasForeignKey("CommandId");
                });

            modelBuilder.Entity("LemadDb.Domain.Entities.Product", b =>
                {
                    b.HasOne("LemadDb.Domain.Entities.Command", "Command")
                        .WithMany()
                        .HasForeignKey("CommandId");

                    b.Navigation("Command");
                });

            modelBuilder.Entity("LemadDb.Domain.User.AddressUser", b =>
                {
                    b.HasOne("LemadDb.Domain.User.AdresseCivique", null)
                        .WithMany("AddressUser")
                        .HasForeignKey("AdresseCiviqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany("CivicAddresses")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LemadDb.Domain.Entities.Command", b =>
                {
                    b.Navigation("ProductIDs");
                });

            modelBuilder.Entity("LemadDb.Domain.User.AdresseCivique", b =>
                {
                    b.Navigation("AddressUser");
                });

            modelBuilder.Entity("LemadDb.Domain.User.ApplicationUser", b =>
                {
                    b.Navigation("CivicAddresses");

                    b.Navigation("Commands");
                });
#pragma warning restore 612, 618
        }
    }
}
