// <auto-generated />
using System;
using LemadDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LemadDb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221016212539_seedEdit3")]
    partial class seedEdit3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LemadDb.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("MaxContractTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<string>("Quote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateNaissance = new DateTime(1981, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teflonso, the spanish GOAT",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Fernando Alonso",
                            Path = "wwwroot/img/products/drivers/FernandoAlonso.png",
                            Price = 20000000m,
                            ProductCategory = 0,
                            Quote = "I am one of the best to have raced in F1. I am probably not fastest in qualifying, or the wet, but I am 9.5 in all areas. I try to benefit from that.",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DateNaissance = new DateTime(1996, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Esteban Ocon",
                            Path = "wwwroot/img/products/drivers/EstebanOcon.png",
                            Price = 5000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DateNaissance = new DateTime(1997, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mad Max",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Max Verstappen",
                            Path = "wwwroot/img/products/drivers/MaxVerstappen.png",
                            Price = 25000000m,
                            ProductCategory = 0,
                            Quote = "Mistakes happen, and they happen to the best of us.",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            DateNaissance = new DateTime(1990, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Checo",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Sergio Perez",
                            Path = "wwwroot/img/products/drivers/SergioPerez.png",
                            Price = 8000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            DateNaissance = new DateTime(1997, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Charles Leclerc",
                            Path = "wwwroot/img/products/drivers/CharlesLeclerc.png",
                            Price = 12000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DateNaissance = new DateTime(1994, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Carlos Sainz",
                            Path = "wwwroot/img/products/drivers/CarlosSainz.png",
                            Price = 10000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            DateNaissance = new DateTime(1985, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Lewis Hamilton",
                            Path = "wwwroot/img/products/drivers/LewisHamilton.png",
                            Price = 40000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            DateNaissance = new DateTime(1998, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 2,
                            MaxContractTime = 5,
                            Name = "George Russell",
                            Path = "wwwroot/img/products/drivers/GeorgeRussell.png",
                            Price = 5000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 9,
                            DateNaissance = new DateTime(1999, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Lando Norris",
                            Path = "wwwroot/img/products/drivers/LandoNorris.png",
                            Price = 20000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            DateNaissance = new DateTime(1989, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Daniel Ricciardo",
                            Path = "wwwroot/img/products/drivers/DanielRicciardo.png",
                            Price = 15000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            DateNaissance = new DateTime(1989, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Valtteri Bottas",
                            Path = "wwwroot/img/products/drivers/ValtteriBottas.png",
                            Price = 10000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            DateNaissance = new DateTime(1999, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Zhou Guanyu",
                            Path = "wwwroot/img/products/drivers/ZhouGuanyu.png",
                            Price = 1000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            DateNaissance = new DateTime(1996, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 18,
                            MaxContractTime = 5,
                            Name = "Pierre Gasly",
                            Path = "wwwroot/img/products/drivers/PierreGasly.png",
                            Price = 5000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 14,
                            DateNaissance = new DateTime(2000, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Yuki Tsunoda",
                            Path = "wwwroot/img/products/drivers/YukiTsunoda.png",
                            Price = 750000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            DateNaissance = new DateTime(1995, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 60,
                            MaxContractTime = 5,
                            Name = "Nicholas Latifi",
                            Path = "wwwroot/img/products/drivers/NicholasLatifi.png",
                            Price = 1000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 16,
                            DateNaissance = new DateTime(1996, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Alexander Albon",
                            Path = "wwwroot/img/products/drivers/AlexanderAlbon.png",
                            Price = 2000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            DateNaissance = new DateTime(1987, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Sebastian Vettel",
                            Path = "wwwroot/img/products/drivers/SebastianVettel.png",
                            Price = 15000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            DateNaissance = new DateTime(1998, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 49,
                            MaxContractTime = 5,
                            Name = "Lance Stroll",
                            Path = "wwwroot/img/products/drivers/LanceStroll.png",
                            Price = 10000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 19,
                            DateNaissance = new DateTime(1992, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 22,
                            MaxContractTime = 5,
                            Name = "Kevin Magnussen",
                            Path = "wwwroot/img/products/drivers/KevinMagnussen.png",
                            Price = 6000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 2
                        },
                        new
                        {
                            Id = 20,
                            DateNaissance = new DateTime(1999, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mick Schumacher",
                            Path = "wwwroot/img/products/drivers/MickSchumacher.png",
                            Price = 1000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mattia Binotto",
                            Path = "wwwroot/img/products/principals/MattiaBinotto.png",
                            Price = 3000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Frédéric Vasseur",
                            Path = "wwwroot/img/products/principals/FredericVasseur.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 2
                        },
                        new
                        {
                            Id = 23,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 25,
                            MaxContractTime = 5,
                            Name = "Franz Tost",
                            Path = "wwwroot/img/products/principals/FranzTost.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Otmar Szafnauer",
                            Path = "wwwroot/img/products/principals/OtmarSzafnauer.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 34,
                            MaxContractTime = 5,
                            Name = "Guenther Steiner",
                            Path = "wwwroot/img/products/principals/GuentherSteiner.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 26,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Andreas Seidl",
                            Path = "wwwroot/img/products/principals/AndreasSeidl.png",
                            Price = 2000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 27,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Toto Wolff",
                            Path = "wwwroot/img/products/principals/TotoWolff.png",
                            Price = 9100000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 13,
                            MaxContractTime = 5,
                            Name = "Christian Horner",
                            Path = "wwwroot/img/products/principals/ChristianHorner.png",
                            Price = 10000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 29,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jost Capito",
                            Path = "wwwroot/img/products/principals/JostCapito.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 1
                        },
                        new
                        {
                            Id = 30,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mike Krack",
                            Path = "wwwroot/img/products/principals/MikeKrack.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 31,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Red Bull Powertrains",
                            Path = "wwwroot/img/products/powerunits/RedBullPowertrains.png",
                            Price = 50000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Ferrari engines",
                            Path = "wwwroot/img/products/powerunits/FerrariEngines.png",
                            Price = 40000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 15,
                            MaxContractTime = 5,
                            Name = "Mercedes engines",
                            Path = "wwwroot/img/products/powerunits/MercedesEngines.png",
                            Price = 35000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 2
                        },
                        new
                        {
                            Id = 34,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Renault engines",
                            Path = "wwwroot/img/products/powerunits/RenaultEngines.png",
                            Price = 30000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 35,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jody Egginton",
                            Path = "wwwroot/img/products/technicalchiefs/JodyEgginton.png",
                            Price = 600000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 36,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Pierre Washe",
                            Path = "wwwroot/img/products/technicalchiefs/PierreWashe.png",
                            Price = 2000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 37,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 10,
                            MaxContractTime = 5,
                            Name = "Enrico Cardile",
                            Path = "wwwroot/img/products/technicalchiefs/EnricoCardile.png",
                            Price = 1500000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 38,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Simone Resta",
                            Path = "wwwroot/img/products/technicalchiefs/SimoneResta.png",
                            Price = 1000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Matt Harman",
                            Path = "wwwroot/img/products/technicalchiefs/MattHarman.png",
                            Price = 1000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mike Elliott",
                            Path = "wwwroot/img/products/technicalchiefs/MikeElliott.png",
                            Price = 1000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 41,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 10,
                            MaxContractTime = 5,
                            Name = "Ben Watkins",
                            Path = "wwwroot/img/products/technicalchiefs/BenWatkins.png",
                            Price = 800000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 42,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Francois-Xavier Demaison",
                            Path = "wwwroot/img/products/technicalchiefs/FrancoisXavierDemaison.png",
                            Price = 750000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 43,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jan Monchaux",
                            Path = "wwwroot/img/products/technicalchiefs/JanMonchaux.png",
                            Price = 500000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 44,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Andrew Green",
                            Path = "wwwroot/img/products/technicalchiefs/AndrewGreen.png",
                            Price = 400000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 45,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Ben Michell",
                            Path = "wwwroot/img/products/raceengineers/BenMichell.png",
                            Price = 2000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 46,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Chris Cronin",
                            Path = "wwwroot/img/products/raceengineers/ChrisCronin.png",
                            Price = 1500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 47,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jorn Becker",
                            Path = "wwwroot/img/products/raceengineers/JornBecker.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 48,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 10,
                            MaxContractTime = 5,
                            Name = "Alex Chan",
                            Path = "wwwroot/img/products/raceengineers/AlexChan.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 49,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mattia Spini",
                            Path = "wwwroot/img/products/raceengineers/MattiaSpini.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 50,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 5,
                            MaxContractTime = 5,
                            Name = "Pierre Hamelin",
                            Path = "wwwroot/img/products/raceengineers/PierreHamelin.png",
                            Price = 800000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 51,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Gary Gannon",
                            Path = "wwwroot/img/products/raceengineers/GaryGannon.png",
                            Price = 750000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 52,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Ed Regan",
                            Path = "wwwroot/img/products/raceengineers/EdRegan.png",
                            Price = 600000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 53,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Gaetan Jego",
                            Path = "wwwroot/img/products/raceengineers/GaetanJego.png",
                            Price = 500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 54,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "James Urwin",
                            Path = "wwwroot/img/products/raceengineers/JamesUrwin.png",
                            Price = 400000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 55,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 5,
                            MaxContractTime = 5,
                            Name = "Josh Pecket",
                            Path = "wwwroot/img/products/raceengineers/JoshPecket.png",
                            Price = 2000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 56,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Karel Loos",
                            Path = "wwwroot/img/products/raceengineers/KarelLoos.png",
                            Price = 1500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 57,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Riccardo Musconi",
                            Path = "wwwroot/img/products/raceengineers/RiccardoMusconi.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 58,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Peter Bonnington",
                            Path = "wwwroot/img/products/raceengineers/PeterBonnington.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 59,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Gianpiero Lambiase",
                            Path = "wwwroot/img/products/raceengineers/GianpieroLambiase.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 60,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Hugh Bird",
                            Path = "wwwroot/img/products/raceengineers/HughBird.png",
                            Price = 800000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 61,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jason Prior",
                            Path = "wwwroot/img/products/raceengineers/JasonPrior.png",
                            Price = 750000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 62,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Christopher Hayes",
                            Path = "wwwroot/img/products/raceengineers/CristopherHayes.png",
                            Price = 600000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 63,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Riccardo Adami",
                            Path = "wwwroot/img/products/raceengineers/RiccardoAdami.png",
                            Price = 500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 64,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Xavier Marcos Pardos",
                            Path = "wwwroot/img/products/raceengineers/XavierMarcosPardos.png",
                            Price = 400000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        });
                });

            modelBuilder.Entity("LemadDb.Domain.User.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EntrepriseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "ff2184b3-e750-49ff-a096-b8d1c0139772",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d616b0f-ae3c-4f28-85c4-6e62ac7e78bf",
                            Email = "admin@lemadrid.com",
                            EmailConfirmed = false,
                            EntrepriseName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LEMADRID.COM",
                            NormalizedUserName = "ADMIN@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIe9ND1PwehUlg4eTonfSMy5iUGMz9jevuEpW6tYxeVY/uUIcJNmhQhihnS8WS80Ug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "166dee84-7d21-4bd4-92d1-44fc2545339c",
                            TwoFactorEnabled = false,
                            UserName = "admin@lemadrid.com"
                        },
                        new
                        {
                            Id = "fd654be7-21ed-4669-9a8b-175ca8f1689c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "086c3e98-4f68-4cb4-a969-802cdb64ad49",
                            Email = "hugo@lemadrid.com",
                            EmailConfirmed = false,
                            EntrepriseName = "Cegep de Saint-Hyacinthe",
                            LockoutEnabled = false,
                            NormalizedEmail = "HUGO@LEMADRID.COM",
                            NormalizedUserName = "HUGO@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKwtMcr+pQmhGz3gnV6BT7lQLKYgurLdjv3qipsVEu0/Dh8FnZY9J+rw4PshuWNH6g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4347944-40ce-45cb-9253-f18af04418f9",
                            TwoFactorEnabled = false,
                            UserName = "hugo@lemadrid.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "fc1b2ed1-a810-43cd-a63e-b5ce89c7b8d3",
                            ConcurrencyStamp = "d7233e5f-7eae-4656-9388-ef3e79e1c3d1",
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "ff2184b3-e750-49ff-a096-b8d1c0139772",
                            RoleId = "fc1b2ed1-a810-43cd-a63e-b5ce89c7b8d3"
                        },
                        new
                        {
                            UserId = "fd654be7-21ed-4669-9a8b-175ca8f1689c",
                            RoleId = "fc1b2ed1-a810-43cd-a63e-b5ce89c7b8d3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
