// <auto-generated />
using System;
using LemadDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LemadDb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LemadDb.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("MaxContractTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<string>("Quote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateNaissance = new DateTime(1981, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teflonso, the spanish GOAT",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Fernando Alonso",
                            Path = "wwwroot/img/products/drivers/FernandoAlonso.png",
                            Price = 20000000m,
                            ProductCategory = 0,
                            Quote = "I am one of the best to have raced in F1. I am probably not fastest in qualifying, or the wet, but I am 9.5 in all areas. I try to benefit from that.",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DateNaissance = new DateTime(1996, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Esteban Ocon",
                            Path = "wwwroot/img/products/drivers/EstebanOcon.png",
                            Price = 5000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DateNaissance = new DateTime(1997, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mad Max",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Max Verstappen",
                            Path = "wwwroot/img/products/drivers/MaxVerstappen.png",
                            Price = 25000000m,
                            ProductCategory = 0,
                            Quote = "Mistakes happen, and they happen to the best of us.",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            DateNaissance = new DateTime(1990, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Checo",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Sergio Perez",
                            Path = "wwwroot/img/products/drivers/SergioPerez.png",
                            Price = 8000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            DateNaissance = new DateTime(1997, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Charles Leclerc",
                            Path = "wwwroot/img/products/drivers/CharlesLeclerc.png",
                            Price = 12000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DateNaissance = new DateTime(1994, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Carlos Sainz",
                            Path = "wwwroot/img/products/drivers/CarlosSainz.png",
                            Price = 10000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            DateNaissance = new DateTime(1985, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Lewis Hamilton",
                            Path = "wwwroot/img/products/drivers/LewisHamilton.png",
                            Price = 40000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            DateNaissance = new DateTime(1998, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 2,
                            MaxContractTime = 5,
                            Name = "George Russell",
                            Path = "wwwroot/img/products/drivers/GeorgeRussell.png",
                            Price = 5000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 9,
                            DateNaissance = new DateTime(1999, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Lando Norris",
                            Path = "wwwroot/img/products/drivers/LandoNorris.png",
                            Price = 20000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            DateNaissance = new DateTime(1989, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Daniel Ricciardo",
                            Path = "wwwroot/img/products/drivers/DanielRicciardo.png",
                            Price = 15000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            DateNaissance = new DateTime(1989, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Valtteri Bottas",
                            Path = "wwwroot/img/products/drivers/ValtteriBottas.png",
                            Price = 10000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            DateNaissance = new DateTime(1999, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Zhou Guanyu",
                            Path = "wwwroot/img/products/drivers/ZhouGuanyu.png",
                            Price = 1000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            DateNaissance = new DateTime(1996, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 80,
                            MaxContractTime = 5,
                            Name = "Pierre Gasly",
                            Path = "wwwroot/img/products/drivers/PierreGasly.png",
                            Price = 5000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 14,
                            DateNaissance = new DateTime(2000, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Yuki Tsunoda",
                            Path = "wwwroot/img/products/drivers/YukiTsunoda.png",
                            Price = 750000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            DateNaissance = new DateTime(1995, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 60,
                            MaxContractTime = 5,
                            Name = "Nicholas Latifi",
                            Path = "wwwroot/img/products/drivers/NicholasLatifi.png",
                            Price = 1000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 16,
                            DateNaissance = new DateTime(1996, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Alexander Albon",
                            Path = "wwwroot/img/products/drivers/AlexanderAlbon.png",
                            Price = 2000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            DateNaissance = new DateTime(1987, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Sebastian Vettel",
                            Path = "wwwroot/img/products/drivers/SebastianVettel.png",
                            Price = 15000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            DateNaissance = new DateTime(1998, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 49,
                            MaxContractTime = 5,
                            Name = "Lance Stroll",
                            Path = "wwwroot/img/products/drivers/LanceStroll.png",
                            Price = 10000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 19,
                            DateNaissance = new DateTime(1992, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 22,
                            MaxContractTime = 5,
                            Name = "Kevin Magnussen",
                            Path = "wwwroot/img/products/drivers/KevinMagnussen.png",
                            Price = 6000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 2
                        },
                        new
                        {
                            Id = 20,
                            DateNaissance = new DateTime(1999, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mick Schumacher",
                            Path = "wwwroot/img/products/drivers/MickSchumacher.png",
                            Price = 1000000m,
                            ProductCategory = 0,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mattia Binotto",
                            Path = "wwwroot/img/products/principals/MattiaBinotto.png",
                            Price = 3000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Frédéric Vasseur",
                            Path = "wwwroot/img/products/principals/FredericVasseur.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 2
                        },
                        new
                        {
                            Id = 23,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 25,
                            MaxContractTime = 5,
                            Name = "Franz Tost",
                            Path = "wwwroot/img/products/principals/FranzTost.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Otmar Szafnauer",
                            Path = "wwwroot/img/products/principals/OtmarSzafnauer.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 34,
                            MaxContractTime = 5,
                            Name = "Guenther Steiner",
                            Path = "wwwroot/img/products/principals/GuentherSteiner.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 26,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Andreas Seidl",
                            Path = "wwwroot/img/products/principals/AndreasSeidl.png",
                            Price = 2000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 27,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Toto Wolff",
                            Path = "wwwroot/img/products/principals/TotoWolff.png",
                            Price = 9100000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 13,
                            MaxContractTime = 5,
                            Name = "Christian Horner",
                            Path = "wwwroot/img/products/principals/ChristianHorner.png",
                            Price = 10000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 29,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jost Capito",
                            Path = "wwwroot/img/products/principals/JostCapito.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 1
                        },
                        new
                        {
                            Id = 30,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mike Krack",
                            Path = "wwwroot/img/products/principals/MikeKrack.png",
                            Price = 1000000m,
                            ProductCategory = 1,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 31,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Red Bull Powertrains",
                            Path = "wwwroot/img/products/powerunits/RedBullPowertrains.png",
                            Price = 50000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Ferrari engines",
                            Path = "wwwroot/img/products/powerunits/FerrariEngines.png",
                            Price = 40000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 15,
                            MaxContractTime = 5,
                            Name = "Mercedes engines",
                            Path = "wwwroot/img/products/powerunits/MercedesEngines.png",
                            Price = 35000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 2
                        },
                        new
                        {
                            Id = 34,
                            DateNaissance = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Renault engines",
                            Path = "wwwroot/img/products/powerunits/RenaultEngines.png",
                            Price = 30000000m,
                            ProductCategory = 2,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 35,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jody Egginton",
                            Path = "wwwroot/img/products/technicalchiefs/JodyEgginton.png",
                            Price = 600000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 36,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Pierre Washe",
                            Path = "wwwroot/img/products/technicalchiefs/PierreWashe.png",
                            Price = 2000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 37,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 10,
                            MaxContractTime = 5,
                            Name = "Enrico Cardile",
                            Path = "wwwroot/img/products/technicalchiefs/EnricoCardile.png",
                            Price = 1500000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 38,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Simone Resta",
                            Path = "wwwroot/img/products/technicalchiefs/SimoneResta.png",
                            Price = 1000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Matt Harman",
                            Path = "wwwroot/img/products/technicalchiefs/MattHarman.png",
                            Price = 1000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mike Elliott",
                            Path = "wwwroot/img/products/technicalchiefs/MikeElliott.png",
                            Price = 1000000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 41,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 10,
                            MaxContractTime = 5,
                            Name = "Ben Watkins",
                            Path = "wwwroot/img/products/technicalchiefs/BenWatkins.png",
                            Price = 800000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 42,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Francois-Xavier Demaison",
                            Path = "wwwroot/img/products/technicalchiefs/FrancoisXavierDemaison.png",
                            Price = 750000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 43,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jan Monchaux",
                            Path = "wwwroot/img/products/technicalchiefs/JanMonchaux.png",
                            Price = 500000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 44,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Andrew Green",
                            Path = "wwwroot/img/products/technicalchiefs/AndrewGreen.png",
                            Price = 400000m,
                            ProductCategory = 4,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 45,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Ben Michell",
                            Path = "wwwroot/img/products/raceengineers/BenMichell.png",
                            Price = 2000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 46,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Chris Cronin",
                            Path = "wwwroot/img/products/raceengineers/ChrisCronin.png",
                            Price = 1500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 47,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jorn Becker",
                            Path = "wwwroot/img/products/raceengineers/JornBecker.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 48,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 10,
                            MaxContractTime = 5,
                            Name = "Alex Chan",
                            Path = "wwwroot/img/products/raceengineers/AlexChan.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 49,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Mattia Spini",
                            Path = "wwwroot/img/products/raceengineers/MattiaSpini.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 50,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 5,
                            MaxContractTime = 5,
                            Name = "Pierre Hamelin",
                            Path = "wwwroot/img/products/raceengineers/PierreHamelin.png",
                            Price = 800000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 51,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Gary Gannon",
                            Path = "wwwroot/img/products/raceengineers/GaryGannon.png",
                            Price = 750000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 52,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Ed Regan",
                            Path = "wwwroot/img/products/raceengineers/EdRegan.png",
                            Price = 600000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 53,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Gaetan Jego",
                            Path = "wwwroot/img/products/raceengineers/GaetanJego.png",
                            Price = 500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 54,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "James Urwin",
                            Path = "wwwroot/img/products/raceengineers/JamesUrwin.png",
                            Price = 400000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 55,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 5,
                            MaxContractTime = 5,
                            Name = "Josh Pecket",
                            Path = "wwwroot/img/products/raceengineers/JoshPecket.png",
                            Price = 2000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 4
                        },
                        new
                        {
                            Id = 56,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Karel Loos",
                            Path = "wwwroot/img/products/raceengineers/KarelLoos.png",
                            Price = 1500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 57,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Riccardo Musconi",
                            Path = "wwwroot/img/products/raceengineers/RiccardoMusconi.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 58,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Peter Bonnington",
                            Path = "wwwroot/img/products/raceengineers/PeterBonnington.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 59,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Gianpiero Lambiase",
                            Path = "wwwroot/img/products/raceengineers/GianpieroLambiase.png",
                            Price = 1000000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 60,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Hugh Bird",
                            Path = "wwwroot/img/products/raceengineers/HughBird.png",
                            Price = 800000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 61,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Jason Prior",
                            Path = "wwwroot/img/products/raceengineers/JasonPrior.png",
                            Price = 750000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 62,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Christopher Hayes",
                            Path = "wwwroot/img/products/raceengineers/CristopherHayes.png",
                            Price = 600000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 63,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Riccardo Adami",
                            Path = "wwwroot/img/products/raceengineers/RiccardoAdami.png",
                            Price = 500000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 64,
                            DateNaissance = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Discount = 0,
                            MaxContractTime = 5,
                            Name = "Xavier Marcos Pardos",
                            Path = "wwwroot/img/products/raceengineers/XavierMarcosPardos.png",
                            Price = 400000m,
                            ProductCategory = 3,
                            Quote = "",
                            Status = 0
                        });
                });

            modelBuilder.Entity("LemadDb.Domain.User.AddressUser", b =>
                {
                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdresseCiviqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AddressId", "UserId");

                    b.HasIndex("AdresseCiviqueId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("AddressUser");

                    b.HasData(
                        new
                        {
                            AddressId = new Guid("dc86213f-5a3a-4c28-8b4e-615b4b140a48"),
                            UserId = new Guid("f41e620d-639e-4cf2-a26d-302ead6302cd")
                        },
                        new
                        {
                            AddressId = new Guid("dc86213f-5a3a-4c28-8b4e-615b4b140a48"),
                            UserId = new Guid("55ee3b18-74e4-4df8-93ac-7ac3b3d06541")
                        },
                        new
                        {
                            AddressId = new Guid("dc86213f-5a3a-4c28-8b4e-615b4b140a48"),
                            UserId = new Guid("65071650-e1bc-4f43-b0aa-61ed1f02cc99")
                        },
                        new
                        {
                            AddressId = new Guid("dc86213f-5a3a-4c28-8b4e-615b4b140a48"),
                            UserId = new Guid("f6a8e6c5-09b0-4bd6-b2e2-f3c78128c8b9")
                        },
                        new
                        {
                            AddressId = new Guid("d00c8c87-f445-41a5-9357-5b4f9d533b06"),
                            UserId = new Guid("2d0dc227-dc5e-4e53-9085-179fa35922d8")
                        });
                });

            modelBuilder.Entity("LemadDb.Domain.User.AdresseCivique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CivicAddresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc86213f-5a3a-4c28-8b4e-615b4b140a48"),
                            Address = "3000 Av. Boullé",
                            City = "Saint-Hyacinthe",
                            Country = "Canada",
                            PostalCode = "J2S 1H9",
                            Province = "Québec"
                        },
                        new
                        {
                            Id = new Guid("d00c8c87-f445-41a5-9357-5b4f9d533b06"),
                            Address = "1899 Henri-Becquerel",
                            City = "Sainte-Julie",
                            Country = "Canada",
                            PostalCode = "J3E 1V6",
                            Province = "Québec"
                        });
                });

            modelBuilder.Entity("LemadDb.Domain.User.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Cellphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "700a7763-b88f-4501-b3ef-91cf55728ba9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "693babff-9f8c-4d7e-93cf-c00b8436b57b",
                            Email = "admin@lemadrid.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LEMADRID.COM",
                            NormalizedUserName = "ADMIN@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENsFIrQ/PXBelrL5rSE+dwFGI4sezws8LExAS5UTe9gnXCm+zYXJZ7sV6YUtA19Xfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5b52bc6f-2bee-4d29-8c81-ffb45a4def99",
                            TwoFactorEnabled = false,
                            UserId = new Guid("d73cd9fd-b661-46d8-8f1a-f09f25459c17"),
                            UserName = "admin@lemadrid.com"
                        },
                        new
                        {
                            Id = "821a5e58-895c-4ab7-b5a8-2725ab6fb71d",
                            AccessFailedCount = 0,
                            Cellphone = "(450)-773-6800",
                            ConcurrencyStamp = "b182d94c-ecc9-4102-b166-5b62c75f21a8",
                            Email = "hugo@lemadrid.com",
                            EmailConfirmed = false,
                            FirstName = "Hugo",
                            LastName = "Lapointe",
                            LockoutEnabled = false,
                            NormalizedEmail = "HUGO@LEMADRID.COM",
                            NormalizedUserName = "HUGO@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEPr2lCIxaEk5OfhwEhZ636lw1B0+oH99fgM4Ac+X/UTuaPrWBkEKON7jmpFIF8/bQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0036b18c-beb1-474c-9a4c-d3966f0c30f3",
                            TwoFactorEnabled = false,
                            UserId = new Guid("f41e620d-639e-4cf2-a26d-302ead6302cd"),
                            UserName = "hugo@lemadrid.com"
                        },
                        new
                        {
                            Id = "b8bf980f-00d7-4e7e-970a-c011b930e1e0",
                            AccessFailedCount = 0,
                            Cellphone = "(450)-649-8594",
                            ConcurrencyStamp = "321a9d8f-13b7-4924-ad9e-4223e98fb731",
                            Email = "karl.mainville@lemadrid.com",
                            EmailConfirmed = false,
                            FirstName = "Karl",
                            LastName = "Mainville",
                            LockoutEnabled = false,
                            NormalizedEmail = "KARL.MAINVILLE@LEMADRID.COM",
                            NormalizedUserName = "KARL.MAINVILLE@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPOVOf5E2z8Stva/3FANNnV9r3rrJmxl8ejHwaQXmjIOZId8n6aagKcf35eJN7EQhA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4ddca9c2-935c-40b0-97cb-3c5ab07e2975",
                            TwoFactorEnabled = false,
                            UserId = new Guid("2d0dc227-dc5e-4e53-9085-179fa35922d8"),
                            UserName = "karl.mainville@lemadrid.com"
                        },
                        new
                        {
                            Id = "528ae69c-c478-4441-b932-3dd54a12e014",
                            AccessFailedCount = 0,
                            Cellphone = "(450)-538-3982",
                            ConcurrencyStamp = "eea6e1d9-8441-45f8-b569-8dd0ea9290c8",
                            Email = "maxime.lefebvre@lemadrid.com",
                            EmailConfirmed = false,
                            FirstName = "Maxime",
                            LastName = "Lefebvre",
                            LockoutEnabled = false,
                            NormalizedEmail = "MAXIME.LEFEBVRE@LEMADRID.COM",
                            NormalizedUserName = "MAXIME.LEFEBVRE@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDkPF8haiJ0I45AObClXy0bn/5HizxI0Z+Ygt3D5/t+5QwIwUaOLRo6Y+GxFqaS4ZA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "55840713-bff4-4eb7-8551-9ee935de76dc",
                            TwoFactorEnabled = false,
                            UserId = new Guid("55ee3b18-74e4-4df8-93ac-7ac3b3d06541"),
                            UserName = "maxime.lefebvre@lemadrid.com"
                        },
                        new
                        {
                            Id = "e068c3dc-b139-479e-8cba-00d7f6d808f0",
                            AccessFailedCount = 0,
                            Cellphone = "(450)-213-5697",
                            ConcurrencyStamp = "966a08c8-f1b9-443b-b3d9-c3b2bb9b6c77",
                            Email = "louis.garceau@lemadrid.com",
                            EmailConfirmed = false,
                            FirstName = "Louis",
                            LastName = "Garceau",
                            LockoutEnabled = false,
                            NormalizedEmail = "LOUIS.GARCEAU@LEMADRID.COM",
                            NormalizedUserName = "LOUIS.GARCEAU@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOn6ttKjsiwYw68V0/OCi8dfAfgThv3XJzSmsVDONmBuZ7/PkgCX0HCuGaAF3UzKBw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "adae878a-1392-4c3f-8a8f-74e1e19cdcf1",
                            TwoFactorEnabled = false,
                            UserId = new Guid("65071650-e1bc-4f43-b0aa-61ed1f02cc99"),
                            UserName = "louis.garceau@lemadrid.com"
                        },
                        new
                        {
                            Id = "8562f120-9efb-4d43-9293-f26abd9a02b8",
                            AccessFailedCount = 0,
                            Cellphone = "(450)-789-4673",
                            ConcurrencyStamp = "f54dcaa6-0e9a-40aa-a2c7-34478653b2e5",
                            Email = "laurent.brochu@lemadrid.com",
                            EmailConfirmed = false,
                            FirstName = "Laurent",
                            LastName = "Brochu",
                            LockoutEnabled = false,
                            NormalizedEmail = "LAURENT.BROCHU@LEMADRID.COM",
                            NormalizedUserName = "LAURENT.BROCHU@LEMADRID.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPLyq35RTnN8FO4ZcrXuKRu2B3d3BbcqkY7inpCk4CAOm4nP4WgEugNDpdtudVDwtA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cc2d10ee-d264-4b99-bd68-332d165eb147",
                            TwoFactorEnabled = false,
                            UserId = new Guid("f6a8e6c5-09b0-4bd6-b2e2-f3c78128c8b9"),
                            UserName = "laurent.brochu@lemadrid.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "ca4659fc-7144-49a2-a12e-8cf2bcec1144",
                            ConcurrencyStamp = "d326ab2c-f8eb-4d75-89a8-479b857f5878",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "4b72a13a-2f6b-4b26-a763-546fde604388",
                            ConcurrencyStamp = "b0a39c25-3345-4f0a-a293-51a7442c3419",
                            Name = "buyer",
                            NormalizedName = "BUYER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "700a7763-b88f-4501-b3ef-91cf55728ba9",
                            RoleId = "ca4659fc-7144-49a2-a12e-8cf2bcec1144"
                        },
                        new
                        {
                            UserId = "821a5e58-895c-4ab7-b5a8-2725ab6fb71d",
                            RoleId = "4b72a13a-2f6b-4b26-a763-546fde604388"
                        },
                        new
                        {
                            UserId = "b8bf980f-00d7-4e7e-970a-c011b930e1e0",
                            RoleId = "4b72a13a-2f6b-4b26-a763-546fde604388"
                        },
                        new
                        {
                            UserId = "528ae69c-c478-4441-b932-3dd54a12e014",
                            RoleId = "4b72a13a-2f6b-4b26-a763-546fde604388"
                        },
                        new
                        {
                            UserId = "e068c3dc-b139-479e-8cba-00d7f6d808f0",
                            RoleId = "4b72a13a-2f6b-4b26-a763-546fde604388"
                        },
                        new
                        {
                            UserId = "8562f120-9efb-4d43-9293-f26abd9a02b8",
                            RoleId = "4b72a13a-2f6b-4b26-a763-546fde604388"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("LemadDb.Domain.User.AddressUser", b =>
                {
                    b.HasOne("LemadDb.Domain.User.AdresseCivique", "AdresseCivique")
                        .WithMany("AddressUser")
                        .HasForeignKey("AdresseCiviqueId");

                    b.HasOne("LemadDb.Domain.User.ApplicationUser", "ApplicationUser")
                        .WithMany("CivicAddress")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("AdresseCivique");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LemadDb.Domain.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LemadDb.Domain.User.AdresseCivique", b =>
                {
                    b.Navigation("AddressUser");
                });

            modelBuilder.Entity("LemadDb.Domain.User.ApplicationUser", b =>
                {
                    b.Navigation("CivicAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
